### ISSUE TITLE
还有3.5的版本的代码吗？

### ISSUE THREAD

**Issue by huansinho** [dayatang/dddlib#10]
你好，由于我们有个遗留项目采用了dddlib的3.5版本，近期需要重启该项目。我在分支和标签里面都找不到3.5这个版本。请问我要怎么找到3.5的代码或者现有的仓库？

**Comment by dayatang** [comment]
建议你采用3.6版本，与3.5应该相差不大

huansinho <notifications@github.com>于2018年7月6日 周五下午2:35写道：

**Comment by dayatang** [comment]
maven代码仓库是https://nexus.dayatang.org/content/repositories/releases/

在 2018年7月6日 下午2:38，杨宇 <dayatang@gmail.com>写道：

**Comment by huansinho** [comment]
我试试改版本， thx！
